version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
      timezone: Europe/Prague
    versioning-strategy: increase
    groups:
      minors-and-patches:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]
      majors:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["major"]
